# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726410dd07c743b2f22f1e3d847a9f0315eefe41fdd5538efe4e0026651b1780b50d826bb04aa1942f5a31d29de76f5301662750a88dbc639ee065095e4b2678

test:
  secret_key_base: 52398e7bfa8ae7eacf297cdb25f9eeefd03c5c99191d146a1d298a8f16f8e637e3420908067e3bd2e3fc7828bca69c3f447910f9023435bcf6c65030451d0674

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
